- name: 'Login'
  uriPattern: 'microsoftlogin(/{@action})'
  defaults:
    '@package': 'DIU.Neos.MicrosoftLogin'
    '@controller': 'Login'
    '@action': 'authenticate'
    '@format': 'html'
  appendExceedingArguments: true
