Neos:
  Neos:
    fusion:
      autoInclude:
        DIU.Neos.MicrosoftLogin: true
    userInterface:
      defaultLanguage: de
      translation:
        autoInclude:
          'DIU.Neos.MicrosoftLogin':
            - '**/*'
  Flow:
    mvc:
      routes:
        'DIU.Neos.MicrosoftLogin':
          position: 'before Neos.Neos'
