DIU:
  Neos:
    MicrosoftLogin:
      credentials:
        clientId: ''
        clientSecret: ''
        redirectUri: 'https://www.yourproject.de/microsoftlogin/authenticate'
      roles:
        default:
          - 'Neos.Neos:Editor'
        admin:
          - 'Neos.Neos:Administrator'
      admins: []
  #    admins:
  #      - 'ad-azure-user@my-domain.com'
